### ISSUE TITLE
Unable to load Material Icons

### ISSUE THREAD

**Issue by akshaygin** [akshay196/notice-board#1]
Not showing material icons on 
https://akshay196.github.io/notice-board/

**Comment by bhavin192** [comment]
The request for font stylesheet is blocked by browser as it tries to load it over `http` and github's `gh-pages` uses `https`

![https-error](https://cloud.githubusercontent.com/assets/5154532/26215080/85db394c-3c1c-11e7-9697-ff1c49edfcb2.png)
